---
system:
  get-uptime:
    command: "uptime"
  view-boot-log:
    command: "cat {{ log }}"
    log:
      from_command: "find /var/log -name boot.log*"
  tail-log:
    command: "tail {{ log_file }} -n {{ num_lines }}"
    log_file:
      values:
        - /var/log/messages
        - /var/log/kern.log
        - /var/log/auth.log
    num_lines: {}
apache:
  get-ips:
    command: "tail /var/log/apache2/access_log"
    num_lines: {}
nginx:
  reload:
    command: 'kill -HUP $(pidof nginx)'
